#!/usr/bin/env sh

# Code spaces
yabai -m space 1 --label personal
yabai -m space 2 --label chat
yabai -m space 3 --label browser
yabai -m space 4 --label code
yabai -m space 5 --label random

# Spaces
yabai -m rule --add app=Discord space=personal
yabai -m rule --add app=WhatsApp space=personal
yabai -m rule --add app=Messages space=personal

yabai -m rule --add app=Slack space=chat
yabai -m rule --add app='Microsoft Teams' space=chat

yabai -m rule --add app=Chrome space=browser
yabai -m rule --add app=Brave space=browser

yabai -m rule --add app=iTerm2 space=code
yabai -m rule --add app=Kitty space=code
yabai -m rule --add app=Code space=code
yabai -m rule --add app='^tmux$' space=code
yabai -m rule --add title='^tmux$' space=code

# Window rules
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add app=Finder manage=off
yabai -m rule --add app=Wally manage=off
yabai -m rule --add app=Calendar manage=off
yabai -m rule --add app=Mail manage=off
yabai -m rule --add app='1Password$' manage=off
yabai -m rule --add app='App Store' manage=off
yabai -m rule --add app='Notion' manage=off
# yabai -m rule --add app='Microsoft Teams' manage=off

# Signals
sudo yabai --load-sa
yabai -m signal --add event=window_destroyed action="bash ~/.local/bin/yabai/window-focus-on-destroy.sh"

# Global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          on
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.00
yabai -m config window_shadow                on

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.75
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on

# Mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# Borders
yabai -m config window_border                off

# General space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   10

# Spacebar padding on top screen
SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:$SPACEBAR_HEIGHT:0
#yabai -m config external_bar main:28:0

echo "yabai configuration loaded.."

#Limelight addon (Kill it and start it each time Yabai starts)
killall limelight &>/dev/null
limelight &>/dev/null &

echo "yabai configuration loaded.."
